return {
	-- {
	-- 	"vhyrro/luarocks.nvim",
	-- 	commit = "1db9093915eb16ba2473cfb8d343ace5ee04130a",
	-- 	pin = false,
	-- 	priority = 1000,
	-- 	config = true,
	-- 	opts = {
	-- 		rocks = { "lua-curl", "nvim-nio", "mimetypes", "xml2lua" },
	-- 	},
	-- },
	-- {
	-- 	"rest-nvim/rest.nvim",
	-- 	commit = "e7843c55f9df6a9db9f97dac180035c6ff895a90",
	-- 	pin = false,
	-- 	ft = "http",
	-- 	dependencies = { "luarocks.nvim" },
	-- 	config = function()
	-- 		require("rest-nvim").setup({
	-- 			result = {
	-- 				split = {
	-- 					horizontal = true,
	-- 				},
	-- 			},
	-- 		})
	-- 		require("which-key").register({
	-- 			h = {
	-- 				name = "[h]elpers",
	-- 				r = { ":Rest run<cr>", "http [r]equest" },
	-- 			},
	-- 		}, { mode = "n", prefix = "<leader>" })
	-- 	end,
	-- },
}
